name: AI Question Generator with Hugging Face

on:
  workflow_dispatch:  # Manual trigger
  repository_dispatch:  # Can be triggered by API calls
    types: [generate-questions]

jobs:
  generate-questions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Generate questions with Hugging Face AI
        env:
          HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
        run: |
          python .github/scripts/ai_processor.py
          
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: generated-questions
          path: results.json
