name: Test DeepSeek Connection

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          pip install requests
          
      - name: Test DeepSeek API connection
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: |
          # Create a Python script to test the connection
          cat > test_deepseek.py << 'EOF'
          import os
          import requests
          import json
          
          def test_connection():
              api_key = os.environ.get('DEEPSEEK_API_KEY')
              if not api_key:
                  print('❌ ERROR: DEEPSEEK_API_KEY not found in environment variables')
                  print('Please make sure you have added DEEPSEEK_API_KEY to your GitHub Secrets')
                  return False
              
              print('🔑 API Key found (first few characters):', api_key[:8] + '...')
              print('🌐 Testing DeepSeek API connection...')
              
              try:
                  response = requests.post(
                      'https://api.deepseek.com/v1/chat/completions',
                      headers={
                          'Authorization': f'Bearer {api_key}',
                          'Content-Type': 'application/json'
                      },
                      json={
                          'model': 'deepseek-chat',
                          'messages': [{'role': 'user', 'content': 'Hello, are you working?'}],
                          'temperature': 0.7,
                          'max_tokens': 50
                      },
                      timeout=30  # 30 second timeout
                  )
                  
                  if response.status_code == 200:
                      print('✅ SUCCESS: DeepSeek API connection successful!')
                      print('Response:', json.dumps(response.json(), indent=2))
                      return True
                  else:
                      print(f'❌ FAILED: API returned status code: {response.status_code}')
                      print('Response:', response.text)
                      
                      # Provide specific error guidance
                      if response.status_code == 401:
                          print('\n🔒 AUTHENTICATION ERROR: Your API key may be invalid or expired')
                          print('Please check your DeepSeek API key in GitHub Secrets')
                      elif response.status_code == 429:
                          print('\n⏰ RATE LIMIT ERROR: You have exceeded your API rate limits')
                      elif response.status_code >= 500:
                          print('\n🔧 SERVER ERROR: DeepSeek API may be experiencing issues')
                      
                      return False
                      
              except requests.exceptions.Timeout:
                  print('❌ TIMEOUT: The request took too long and timed out')
                  return False
              except requests.exceptions.ConnectionError:
                  print('❌ CONNECTION ERROR: Could not connect to DeepSeek API')
                  print('Please check your internet connection or try again later')
                  return False
              except Exception as e:
                  print(f'❌ UNEXPECTED ERROR: {str(e)}')
                  return False
          
          if __name__ == '__main__':
              success = test_connection()
              exit(0 if success else 1)
          EOF
          
          # Run the test script
          python test_deepseek.py
